"""baseline

Revision ID: 8696785e21fe
Revises: 
Create Date: 2026-07-21 14:59:12.293783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8696785e21fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pigments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='san_xuat', nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('hidden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_mau', sa.Text(), nullable=False),
    sa.Column('ten_mau', sa.Text(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('qr_code_path', sa.Text(), nullable=True),
    sa.Column('hex_color', sa.Text(), nullable=True),
    sa.Column('trang_thai_duyet', sa.Text(), server_default='CHO_DUYET', nullable=False),
    sa.Column('duyet_boi', sa.Integer(), nullable=True),
    sa.Column('duyet_luc', sa.DateTime(), nullable=True),
    sa.Column('ly_do_tu_choi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['duyet_boi'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_mau')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission')
    )
    op.create_table('color_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('loai_anh', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_pigments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('pigment_id', sa.Integer(), nullable=False),
    sa.Column('ty_le', sa.REAL(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pigment_id'], ['pigments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color_id', 'pigment_id')
    )
    op.create_table('color_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('trang_thai_duyet', sa.Text(), server_default='CHO_DUYET', nullable=False),
    sa.Column('duyet_boi', sa.Integer(), nullable=True),
    sa.Column('duyet_luc', sa.DateTime(), nullable=True),
    sa.Column('ly_do_tu_choi', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['duyet_boi'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color_id', 'version_number')
    )
    op.create_table('color_version_pigments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('pigment_id', sa.Integer(), nullable=False),
    sa.Column('ty_le', sa.REAL(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['pigment_id'], ['pigments.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['color_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'pigment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color_version_pigments')
    op.drop_table('color_versions')
    op.drop_table('color_pigments')
    op.drop_table('color_images')
    op.drop_table('user_permissions')
    op.drop_table('colors')
    op.drop_table('activity_logs')
    op.drop_table('users')
    op.drop_table('pigments')
    # ### end Alembic commands ###
