"""empty message

Revision ID: c61e57d23012
Revises: 8696785e21fe
Create Date: 2026-07-22 14:01:42.099149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61e57d23012'
down_revision = '8696785e21fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weighing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.Text(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('ma_mau', sa.Text(), nullable=False),
    sa.Column('ten_mau', sa.Text(), nullable=True),
    sa.Column('tong_thanh_pham_g', sa.REAL(), nullable=False),
    sa.Column('ty_le_pigment', sa.REAL(), nullable=False),
    sa.Column('nguoi_tao', sa.Text(), nullable=False),
    sa.Column('ngay_tao', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weighing_records')
    # ### end Alembic commands ###
